<html>
	<head>
		<title>Sharkey's Wing and Rib Joint</title>
		<link rel="stylesheet" href="sharkeys.css" type='text/css'>
	</head>
	
	<body background='./background.jpg'>
		<?php require_once('navbar.php'); ?>
		
		<div class='content'>
			<div class='header'>
				<img src='http://nebula.wsimg.com/f7e261adb16376df07825ca79d49b2ca?AccessKeyId=3AF9510BFFDF9C352E2C&disposition=0&alloworigin=1'/>
				<h1>Sharkey's Wing and Rib Joint!</h1>
				
				<div class='slideshow'>
					<div class='sharkeySlide'></div>
				</div>
				
			</div>
			
			<div class='welcome'>
				<h3>Welcome!</h3>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p><p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p><p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p><p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
				<p>
					Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis felis vel ligula tempor venenatis at ac enim. Nullam maximus, erat ac venenatis lacinia, elit velit hendrerit tortor, sed mollis massa ipsum eu purus. Quisque tristique nec metus sit amet porta. Nunc fermentum vulputate nunc in porta. Nullam auctor mollis mi. Vestibulum sit amet rhoncus arcu. Vivamus vel urna eu metus posuere fringilla non quis lectus. Donec sollicitudin neque ac risus egestas condimentum. Phasellus fermentum libero ut convallis egestas.
					<br>
					Sed cursus rhoncus magna ut semper. Vestibulum non elit dui. Sed eleifend pretium justo et interdum. Mauris risus ligula, ullamcorper at lectus a, facilisis molestie ante. Donec bibendum mollis lectus. Nam ac justo eu est molestie tristique vitae ut justo. Curabitur sed diam a diam ultrices suscipit.
					<br>
					Donec vestibulum erat non efficitur imperdiet. Proin sollicitudin erat lorem, quis lobortis turpis tempus at. Maecenas ut leo at odio vulputate consectetur. Praesent interdum ornare tristique. In semper tellus a mauris mollis, et auctor nulla consectetur. Ut volutpat dolor felis, id consectetur mi aliquam et. Nam consequat ullamcorper dictum. Maecenas ut libero iaculis, luctus lorem quis, varius nisi. Sed nec justo id leo venenatis interdum. Fusce scelerisque diam mauris, quis cursus lectus rhoncus ac. Vestibulum est nulla, facilisis quis tortor auctor, interdum blandit magna. Nulla ac nunc vulputate, auctor turpis vehicula, imperdiet libero.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas vestibulum massa lacinia pulvinar dictum. Donec rutrum lorem lorem, finibus hendrerit arcu commodo vitae. Integer ut fermentum ipsum. Morbi imperdiet at erat non sollicitudin. Phasellus sodales tortor lorem, id aliquet enim suscipit non. Vivamus pulvinar nisi sed tortor feugiat, ut scelerisque velit commodo. Ut finibus eros ut nulla finibus, vel varius dolor viverra. Vivamus sit amet posuere elit. Ut cursus tempus ipsum nec finibus. Suspendisse consequat viverra lacus, commodo egestas odio varius ut. Donec nec lacinia tortor. Etiam sollicitudin nibh convallis turpis placerat mattis. Donec ultricies, purus et eleifend vehicula, est nisl tempor neque, eget fermentum dui eros vel eros.
					<br>
					Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed ac arcu ullamcorper, sodales justo a, consectetur justo. Suspendisse sed elit ut tellus fringilla imperdiet. Maecenas luctus est et enim luctus, vel vestibulum sem pulvinar. Nunc a pellentesque ipsum, vel dictum urna. Maecenas egestas eros ac pellentesque auctor. Mauris sed orci eu massa dapibus mattis vitae porta metus. Duis leo justo, dapibus vitae suscipit id, gravida nec enim.
				</p>
			</div>
		</div>
		
		<?php require_once('footer.php'); ?>
	</body>
</html>